version: "3.0"
services:
  reader1:
    build: ./readers/
    container_name: reader1
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      - port=3000
  reader2:
    build: ./readers/
    container_name: reader2
    ports:
      - "4000:4000"
    environment:
      - port=4000
    networks:
      - app_network
  writer1:
    build: ./writers
    container_name: writer1
    ports:
      - "5000:5000"
    environment:
      - port=5000
    networks:
      - app_network
  writer2:
    build: ./writers
    container_name: writer2
    ports:
      - "6000:6000"
    environment:
      - port=6000
    networks:
      - app_network
  writer3:
    build: ./writers
    container_name: writer3
    ports:
      - "7000:7000"
    environment:
      - port=7000
    networks:
      - app_network
  admin:
    build: ./admin
    container_name: admin
    ports:
      - "9000:9000"
    environment:
      - port=9000
    networks:
      - app_network

networks:
  app_network:
